import * as stylex from '@stylexjs/stylex';

export const chatBackupsStyles = stylex.create({
    list: {
        display: 'flex',
        flexDirection: 'column',
        gap: 5,
        maxHeight: 'min(25dvh, 250px)',
        overflowY: 'auto',
        borderRadius: 10,
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        padding: 5,
        width: '100%',
    },
    item: {
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        width: '100%',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        borderRadius: 5,
        padding: '5px 7px',
        fontSize: 'smaller',
        background: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 72%, var(--black70a) 28%)',
    },
    itemName: {
        opacity: 0.75,
        flexGrow: 1,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    itemInfo: {
        opacity: 0.75,
    },
    itemActions: {
        display: 'flex',
        alignItems: 'center',
        gap: 5,
    },
    itemActionButton: {
        fontSize: 'var(--mainFontSize)',
        backgroundColor: 'transparent',
        borderWidth: 0,
    },
    dialogOverlay: {
        position: 'fixed',
        inset: 0,
        zIndex: 20000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'color-mix(in srgb, var(--black70a) 72%, transparent)',
        padding: 20,
    },
    dialog: {
        // Neutralize UA <dialog> centering/sizing: the overlay owns placement.
        position: 'static',
        margin: 0,
        maxWidth: 'none',
        maxHeight: 'none',
        color: 'inherit',
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
        width: 'min(720px, 90vw)',
        height: 'min(560px, 80vh)',
        padding: 15,
        borderRadius: 10,
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        backgroundColor: 'var(--SmartThemeBlurTintColor)',
        boxShadow: '0 12px 40px color-mix(in srgb, var(--black70a) 60%, transparent)',
    },
    dialogCompact: {
        height: 'auto',
        maxWidth: 'min(420px, 90vw)',
    },
    dialogTitle: {
        margin: 0,
        fontSize: 'calc(var(--mainFontSize) * 1.1)',
        fontWeight: 600,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    dialogTextarea: {
        flex: 1,
        width: '100%',
        height: '100%',
        margin: 0,
        resize: 'none',
    },
    dialogActions: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 10,
    },
    dialogText: {
        margin: 0,
        fontSize: 'var(--mainFontSize)',
    },
});
