import * as stylex from '@stylexjs/stylex';

export const dataMaidStyles = stylex.create({
    overlay: {
        position: 'fixed',
        inset: 0,
        zIndex: 20000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'color-mix(in srgb, var(--black70a) 72%, transparent)',
        padding: 20,
    },
    dialog: {
        // Neutralize UA <dialog> centering/sizing: the overlay owns placement.
        position: 'static',
        margin: 0,
        maxWidth: 'none',
        maxHeight: 'none',
        color: 'inherit',
        display: 'flex',
        flexDirection: 'column',
        gap: 5,
        width: 'min(860px, 92vw)',
        height: 'min(640px, 85vh)',
        padding: 15,
        borderRadius: 10,
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        backgroundColor: 'var(--SmartThemeBlurTintColor)',
        boxShadow: '0 12px 40px color-mix(in srgb, var(--black70a) 60%, transparent)',
        overflow: 'hidden',
    },
    dialogHeader: {
        display: 'flex',
        gap: 10,
        alignItems: 'center',
        textAlign: 'left',
    },
    headerInfo: {
        flex: 1,
        margin: 0,
        padding: '5px 10px',
    },
    spinner: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100%',
    },
    placeholder: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: '1.05em',
    },
    resultsList: {
        textAlign: 'left',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        overflowY: 'auto',
        height: '100%',
        flexGrow: 1,
    },
    category: {
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        borderRadius: 10,
        padding: '0 10px',
    },
    categoryToggle: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        cursor: 'pointer',
        userSelect: 'none',
    },
    categoryToggleButton: {
        display: 'flex',
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-between',
        marginRight: 5,
        padding: '0 5px',
        textAlign: 'left',
        backgroundColor: 'transparent',
        borderWidth: 0,
        cursor: 'pointer',
    },
    categoryDeleteButton: {
        backgroundColor: 'transparent',
        borderWidth: 0,
    },
    categoryHeader: {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginRight: 5,
        padding: '0 5px',
    },
    categoryDetails: {
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
    },
    categoryName: {
        flex: 3,
        fontWeight: 'bold',
        fontSize: '1.1em',
    },
    categoryInfo: {
        flex: 1,
        display: 'flex',
        alignItems: 'baseline',
        gap: 5,
    },
    categoryContent: {
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        padding: 5,
        borderRadius: 10,
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 72%, var(--black70a) 28%)',
        margin: '10px 0',
    },
    categoryItems: {
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
    },
    item: {
        display: 'flex',
        flexDirection: 'column',
        padding: 5,
        width: '100%',
        borderBottomWidth: 1,
        borderBottomStyle: 'solid',
        borderBottomColor: 'var(--SmartThemeBorderColor)',
        ':last-child': {
            borderBottomWidth: 0,
            borderBottomStyle: 'none',
        },
    },
    itemHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: 5,
    },
    itemName: {
        display: 'flex',
        flex: 1,
        alignItems: 'baseline',
        gap: 2,
        wordBreak: 'break-all',
    },
    itemActions: {
        display: 'flex',
        alignItems: 'center',
        gap: 5,
    },
    itemActionButton: {
        fontSize: '0.9em',
    },
    itemInfo: {
        display: 'flex',
        alignItems: 'baseline',
        gap: 5,
    },
    textView: {
        width: '100%',
        height: '100%',
        flex: 1,
        fontFamily: 'var(--monoFontFamily)',
        resize: 'none',
        fontSize: '0.95em',
        margin: 0,
    },
    imageView: {
        width: '100%',
        height: '100%',
        flex: 1,
        objectFit: 'contain',
        minHeight: 0,
    },
    viewerDialog: {
        // Neutralize UA <dialog> centering/sizing: the overlay owns placement.
        position: 'static',
        margin: 0,
        maxWidth: 'none',
        maxHeight: 'none',
        color: 'inherit',
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
        width: 'min(860px, 92vw)',
        height: 'min(640px, 85vh)',
        padding: 15,
        borderRadius: 10,
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        backgroundColor: 'var(--SmartThemeBlurTintColor)',
        boxShadow: '0 12px 40px color-mix(in srgb, var(--black70a) 60%, transparent)',
        overflow: 'hidden',
    },
    confirmDialog: {
        // Neutralize UA <dialog> centering/sizing: the overlay owns placement.
        position: 'static',
        margin: 0,
        maxHeight: 'none',
        color: 'inherit',
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
        maxWidth: 'min(460px, 90vw)',
        padding: 15,
        borderRadius: 10,
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        backgroundColor: 'var(--SmartThemeBlurTintColor)',
        boxShadow: '0 12px 40px color-mix(in srgb, var(--black70a) 60%, transparent)',
    },
    dialogActions: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 10,
    },
    dialogText: {
        margin: 0,
        fontSize: 'var(--mainFontSize)',
        whiteSpace: 'pre-wrap',
    },
});
