import * as stylex from '@stylexjs/stylex';

const narrowScreen = '@media screen and (max-width: 800px)';
const shellChromeNarrow = '@container (max-width: 1180px)';

export const workspacePanelStyles = stylex.create({
    statusBadge: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        borderRadius: '999px',
        fontSize: 'calc(var(--mainFontSize) * 0.76)',
        lineHeight: 1.15,
        padding: '2px 8px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 70%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 82%, transparent)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 80%, var(--SmartThemeBlurTintColor) 20%)',
    },
    statusBadgeLoading: {
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 42%, transparent)',
        color: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 72%, var(--SmartThemeBodyColor) 28%)',
    },
    statusBadgeError: {
        borderColor: 'color-mix(in srgb, var(--error-color, var(--ember-red)) 46%, transparent)',
        color: 'var(--error-color, var(--ember-red))',
    },
    legacySlotStatus: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        borderRadius: '999px',
        fontSize: 'calc(var(--mainFontSize) * 0.76)',
        lineHeight: 1.15,
    },
    legacySlotStatusReady: {
        color: 'var(--success-green)',
    },
    legacySlotStatusPending: {
        color: 'var(--warning)',
        fontWeight: 600,
    },
    legacySlot: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '8px',
    },
    recovery: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    recoveryActions: {
        display: 'inline-flex',
        flexWrap: 'wrap',
        gap: '6px',
        width: {
            default: null,
            [narrowScreen]: '100%',
        },
    },
    recoveryActionButton: {
        minHeight: '26px',
    },
});

export const workspaceShellStyles = stylex.create({
    chrome: {
        display: 'grid',
        gridTemplateColumns: 'minmax(0, 1fr) auto',
        alignItems: 'center',
        gap: '8px',
        height: '100%',
        padding: '4px 10px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 78%, transparent)',
        borderRadius: '0 0 9px 9px',
        background: 'linear-gradient(90deg, color-mix(in srgb, var(--SmartThemeQuoteColor) 13%, transparent), transparent 32%), color-mix(in srgb, var(--SmartThemeBlurTintColor) 90%, var(--black70a) 10%)',
        boxShadow: '0 4px 24px color-mix(in srgb, var(--black70a) 72%, transparent)',
        backdropFilter: 'blur(var(--SmartThemeBlurStrength))',
        WebkitBackdropFilter: 'blur(var(--SmartThemeBlurStrength))',
        containerType: 'inline-size',
        pointerEvents: 'auto',
    },
    context: {
        display: 'flex',
        minWidth: 0,
        alignItems: 'center',
        paddingInline: {
            default: '4px',
            [narrowScreen]: '2px',
        },
        overflow: 'hidden',
    },
    title: {
        flex: '1 1 auto',
        minWidth: 0,
        overflow: 'hidden',
        color: 'var(--SmartThemeBodyColor)',
        fontSize: 'calc(var(--mainFontSize) * 1.02)',
        fontWeight: 700,
        lineHeight: 1.25,
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    nav: {
        display: 'flex',
        flex: '0 0 auto',
        alignItems: 'center',
        gap: '4px',
        paddingBlock: '1px',
    },
    navButton: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 0,
        flex: '0 0 auto',
        minHeight: '28px',
        gap: '5px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: {
            default: 'color-mix(in srgb, var(--SmartThemeBorderColor) 70%, transparent)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 46%, var(--SmartThemeBorderColor) 54%)',
            ':focus-visible': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 46%, var(--SmartThemeBorderColor) 54%)',
        },
        borderRadius: '7px',
        padding: '3px 7px',
        backgroundColor: {
            default: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 76%, var(--black50a) 24%)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 13%, var(--SmartThemeBlurTintColor) 87%)',
            ':focus-visible': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 13%, var(--SmartThemeBlurTintColor) 87%)',
        },
        color: 'var(--SmartThemeBodyColor)',
        font: 'inherit',
        fontSize: 'calc(var(--mainFontSize) * 0.83)',
        lineHeight: 1.2,
        cursor: 'pointer',
        outline: {
            ':focus-visible': '1px solid var(--interactable-outline-color)',
        },
        outlineOffset: {
            ':focus-visible': '2px',
        },
    },
    navButtonActive: {
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 72%, var(--SmartThemeBorderColor) 28%)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 20%, var(--SmartThemeBlurTintColor) 80%)',
        boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--SmartThemeQuoteColor) 34%, transparent)',
    },
    navButtonLabel: {
        [shellChromeNarrow]: {
            position: 'absolute',
            width: '1px',
            height: '1px',
            margin: '-1px',
            overflow: 'hidden',
            clip: 'rect(0 0 0 0)',
            clipPath: 'inset(50%)',
            whiteSpace: 'nowrap',
        },
    },
});

export const authoringStyles = stylex.create({
    panel: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        padding: '8px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 72%, transparent)',
        borderRadius: '10px',
        background: 'linear-gradient(color-mix(in srgb, var(--SmartThemeBlurTintColor) 86%, transparent), color-mix(in srgb, var(--SmartThemeBlurTintColor) 86%, transparent)), color-mix(in srgb, black 88%, var(--SmartThemeBodyColor) 12%)',
    },
    panelHeader: {
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: '8px',
    },
    panelKicker: {
        margin: 0,
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 72%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.86)',
    },
    panelWarning: {
        borderRadius: '999px',
        padding: '3px 8px',
        fontSize: 'calc(var(--mainFontSize) * 0.84)',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 62%, transparent)',
        background: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 68%, transparent)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 92%, transparent)',
    },
    fields: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    fieldLabel: {
        display: 'flex',
        alignItems: 'baseline',
        gap: '6px',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 78%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.88)',
        fontWeight: 600,
    },
    fieldMeta: {
        marginLeft: 'auto',
        fontWeight: 400,
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 50%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.76)',
        whiteSpace: 'nowrap',
    },
    fieldWarning: {
        color: 'var(--warning)',
    },
    panelActions: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '5px',
        alignItems: 'center',
        position: 'sticky',
        bottom: 0,
        zIndex: 2,
        marginInline: '-6px',
        borderTopWidth: '1px',
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 48%, transparent)',
        padding: '8px 6px 6px',
        marginTop: '10px',
        background: 'linear-gradient(color-mix(in srgb, var(--SmartThemeBlurTintColor) 86%, transparent), color-mix(in srgb, var(--SmartThemeBlurTintColor) 86%, transparent)), color-mix(in srgb, black 88%, var(--SmartThemeBodyColor) 12%)',
        boxShadow: '0 -8px 18px color-mix(in srgb, black 22%, transparent)',
    },
    iconAction: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        margin: 0,
        padding: '3px 6px',
        borderWidth: 0,
        borderRadius: '4px',
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 18%, transparent)',
        },
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 58%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
        cursor: 'pointer',
        opacity: { ':disabled': 0.35 },
    },
    greetingAdd: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '6px',
        margin: 0,
        padding: '6px 10px',
        borderWidth: '1px',
        borderStyle: 'dashed',
        borderColor: {
            default: 'color-mix(in srgb, var(--SmartThemeBorderColor) 58%, transparent)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 55%, transparent)',
        },
        borderRadius: '8px',
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 10%, transparent)',
        },
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 62%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.84)',
        cursor: 'pointer',
        transition: 'border-color 0.15s ease, background-color 0.15s ease',
    },

    saveButton: {
        background: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 26%, var(--SmartThemeBlurTintColor))',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 65%, transparent)',
        color: 'var(--SmartThemeBodyColor)',
        fontWeight: 700,
    },
    toolAction: {
        opacity: 0.82,
        filter: 'grayscale(0.35)',
        background: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 72%, transparent)',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 58%, transparent)',
    },
    dangerButton: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '5px',
        whiteSpace: 'nowrap',
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeEmColor) 18%, transparent)',
        },
        borderColor: 'color-mix(in srgb, var(--SmartThemeEmColor) 55%, transparent)',
        color: 'var(--SmartThemeEmColor)',
    },
    footerStatus: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontSize: 'calc(var(--mainFontSize) * 0.8)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 66%, transparent)',
        whiteSpace: 'nowrap',
    },
    footerDot: {
        display: 'inline-block',
        width: '6px',
        height: '6px',
        borderRadius: '999px',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBodyColor) 45%, transparent)',
    },
    footerDotBusy: {
        backgroundColor: 'var(--SmartThemeQuoteColor)',
        boxShadow: '0 0 4px color-mix(in srgb, var(--SmartThemeQuoteColor) 70%, transparent)',
    },
    footerDotError: {
        backgroundColor: 'var(--SmartThemeEmColor)',
        boxShadow: '0 0 4px color-mix(in srgb, var(--SmartThemeEmColor) 70%, transparent)',
    },
    footerTools: {
        display: 'flex',
        alignItems: 'center',
        gap: '5px',
        marginLeft: 'auto',
    },
    actionMenuWrap: {
        position: 'relative',
        display: 'inline-flex',
    },
    actionMenu: {
        position: 'absolute',
        bottom: 'calc(100% + 4px)',
        right: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
        minWidth: 'calc(var(--mainFontSize) * 13)',
        maxHeight: 'min(60vh, 420px)',
        overflowY: 'auto',
        padding: '4px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        borderRadius: '6px',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 92%, var(--SmartThemeBodyColor) 4%)',
        boxShadow: '0 10px 24px var(--SmartThemeShadowColor)',
        zIndex: 30,
    },
    actionMenuItem: {
        display: 'flex',
        alignItems: 'center',
        width: '100%',
        padding: '6px 10px',
        borderWidth: 0,
        borderRadius: '4px',
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 22%, transparent)',
        },
        color: 'var(--SmartThemeBodyColor)',
        fontSize: 'calc(var(--mainFontSize) * 0.92)',
        textAlign: 'left',
        cursor: 'pointer',
        outlineWidth: { ':focus-visible': '1px' },
        outlineStyle: { ':focus-visible': 'solid' },
        outlineColor: { ':focus-visible': 'var(--interactable-outline-color)' },
        outlineOffset: { ':focus-visible': '-1px' },
    },
    actionMenuItemDanger: {
        color: 'var(--SmartThemeEmColor)',
        borderTopWidth: '1px',
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 52%, transparent)',
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        marginTop: '2px',
        paddingTop: '7px',
        backgroundColor: {
            ':hover': 'color-mix(in srgb, red 26%, transparent)',
        },
    },
    section: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        borderTopWidth: '1px',
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 42%, transparent)',
        paddingTop: '8px',
    },
    sectionFirst: {
        borderTopWidth: 0,
        paddingTop: 0,
    },
    fieldRow: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
        alignItems: 'flex-start',
    },
    fieldRowItem: {
        flex: '1 1 0',
        minWidth: 'calc(var(--mainFontSize) * 7)',
    },

    control: {
        borderColor: {
            default: null,
            ':focus': 'var(--SmartThemeQuoteColor)',
            ':focus-visible': 'var(--SmartThemeQuoteColor)',
        },
        boxShadow: {
            default: null,
            ':focus': '0 0 0 2px color-mix(in srgb, var(--SmartThemeQuoteColor) 28%, transparent)',
            ':focus-visible': '0 0 0 2px color-mix(in srgb, var(--SmartThemeQuoteColor) 28%, transparent)',
        },
        transition: 'border-color 0.15s ease, box-shadow 0.15s ease',
    },
    textareaAuto: {
        resize: 'none',
        overflowY: 'auto',
        maxHeight: '38vh',
    },
    textareaPreview: {
        maxHeight: '9.5em',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
        zIndex: 9000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '24px',
        backgroundColor: 'color-mix(in srgb, black 55%, transparent)',
    },
    modalCard: {
        // Neutralize UA <dialog> centering/sizing: the overlay owns placement.
        position: 'static',
        margin: 0,
        maxWidth: 'none',
        maxHeight: 'none',
        color: 'inherit',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        width: 'min(720px, 92vw)',
        padding: '12px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        borderRadius: '12px',
        background: 'linear-gradient(color-mix(in srgb, var(--SmartThemeBlurTintColor) 92%, transparent), color-mix(in srgb, var(--SmartThemeBlurTintColor) 92%, transparent)), color-mix(in srgb, black 90%, var(--SmartThemeBodyColor) 10%)',
        boxShadow: '0 18px 48px var(--SmartThemeShadowColor)',
    },
    modalHead: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    modalTitle: {
        fontWeight: 700,
        fontSize: 'calc(var(--mainFontSize) * 1.02)',
    },
    modalTextarea: {
        minHeight: '42vh',
        maxHeight: '62vh',
    },
    modalHint: {
        margin: 0,
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 52%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
    },
    dirtyDot: {
        display: 'inline-block',
        width: '5px',
        height: '5px',
        borderRadius: '999px',
        marginLeft: '5px',
        verticalAlign: 'middle',
        backgroundColor: 'var(--SmartThemeQuoteColor)',
        boxShadow: '0 0 4px color-mix(in srgb, var(--SmartThemeQuoteColor) 70%, transparent)',
    },
    heroRow: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '10px',
    },
    heroAvatar: {
        position: 'relative',
        flexShrink: 0,
        width: '56px',
        height: '56px',
        borderRadius: '12px',
        overflow: 'hidden',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: {
            default: 'color-mix(in srgb, var(--SmartThemeBorderColor) 62%, transparent)',
            ':hover': 'var(--SmartThemeQuoteColor)',
        },
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 82%, transparent)',
        cursor: 'pointer',
        transition: 'border-color 0.15s ease',
    },
    heroAvatarImg: {
        display: 'block',
        width: '100%',
        height: '100%',
        objectFit: 'cover',
    },
    heroAvatarOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        display: 'flex',
        alignItems: 'flex-end',
        justifyContent: 'center',
        paddingBottom: '4px',
        height: '46%',
        backgroundImage: 'linear-gradient(transparent, color-mix(in srgb, black 58%, transparent))',
        color: 'color-mix(in srgb, white 88%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
        pointerEvents: 'none',
    },
    heroMain: {
        flex: '1 1 auto',
        minWidth: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    heroNameInput: {
        fontSize: 'calc(var(--mainFontSize) * 1.12)',
        fontWeight: 700,
    },
    heroMetaRow: {
        display: 'flex',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '6px',
    },
    favToggle: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '5px',
        margin: 0,
        padding: '3px 9px',
        borderRadius: '999px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: {
            default: 'color-mix(in srgb, var(--SmartThemeBorderColor) 58%, transparent)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 55%, transparent)',
        },
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 12%, transparent)',
        },
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 62%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.84)',
        cursor: 'pointer',
        transition: 'border-color 0.15s ease, background-color 0.15s ease, color 0.15s ease',
        outlineWidth: { ':focus-visible': '1px' },
        outlineStyle: { ':focus-visible': 'solid' },
        outlineColor: { ':focus-visible': 'var(--interactable-outline-color)' },
        outlineOffset: { ':focus-visible': '2px' },
    },
    favToggleActive: {
        color: 'var(--SmartThemeQuoteColor)',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 55%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 14%, transparent)',
    },
    metaChip: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        borderRadius: '999px',
        padding: '3px 9px',
        fontSize: 'calc(var(--mainFontSize) * 0.8)',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 48%, transparent)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 66%, transparent)',
        whiteSpace: 'nowrap',
    },
    advancedSection: {
        display: 'flex',
        flexDirection: 'column',
        borderTopWidth: '1px',
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 52%, transparent)',
    },
    advancedHead: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        paddingTop: '7px',
    },
    advancedToggle: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        margin: 0,
        padding: '0',
        borderWidth: 0,
        backgroundColor: {
            default: 'transparent',
            ':hover': 'transparent',
        },
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 82%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.92)',
        fontWeight: 700,
        textAlign: 'left',
        cursor: 'pointer',
        outlineWidth: { ':focus-visible': '1px' },
        outlineStyle: { ':focus-visible': 'solid' },
        outlineColor: { ':focus-visible': 'var(--interactable-outline-color)' },
        outlineOffset: { ':focus-visible': '2px' },
    },
    advancedToggleIcon: {
        fontSize: 'calc(var(--mainFontSize) * 0.8)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 62%, transparent)',
        transform: 'rotate(-90deg)',
        transition: 'transform 0.15s ease',
    },
    advancedToggleIconOpen: {
        transform: 'rotate(0deg)',
    },
    advancedChips: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '4px',
        marginLeft: 'auto',
        justifyContent: 'flex-end',
        minWidth: 0,
    },
    advancedChipButton: {
        borderRadius: '999px',
        padding: '1px 8px',
        fontSize: 'calc(var(--mainFontSize) * 0.76)',
        fontWeight: 600,
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 45%, transparent)',
        color: 'var(--SmartThemeQuoteColor)',
        whiteSpace: 'nowrap',
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 18%, transparent)',
        },
        cursor: 'pointer',
    },
    advancedHint: {
        margin: 0,
        padding: '4px 2px 0',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 56%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.8)',
    },
    advancedClip: {
        display: 'grid',
        gridTemplateRows: '0fr',
        transition: 'grid-template-rows 0.18s ease',
    },
    advancedClipOpen: {
        gridTemplateRows: '1fr',
    },
    advancedBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        paddingTop: '10px',
        minHeight: 0,
        overflow: 'hidden',
    },
    advancedSubgroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    subsectionLabel: {
        margin: 0,
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 62%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
        fontWeight: 700,
        letterSpacing: '0.04em',
        textTransform: 'uppercase',
        borderBottomWidth: '1px',
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 36%, transparent)',
        paddingBottom: '3px',
    },
});

export const characterLibraryStyles = stylex.create({
    toolbar: {
        display: 'flex',
        flexDirection: 'column',
        gap: '7px',
        padding: '1px 0 2px',
    },
    toolbarAction: {
        margin: 0,
        minHeight: 'calc(var(--mainFontSize) * 1.85)',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 72%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 72%, transparent)',
    },
    toolbarActionIcon: {
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
    },
    toolbarActionCompact: {
        width: 'calc(var(--mainFontSize) * 1.9)',
        minWidth: 'calc(var(--mainFontSize) * 1.9)',
        minHeight: 'calc(var(--mainFontSize) * 1.9)',
        padding: '3px',
    },
    toolbarActionFull: {
        gap: '5px',
        paddingInline: '8px',
    },
    toolbarActions: {
        display: 'flex',
        flexWrap: 'nowrap',
        gap: '8px',
        alignItems: 'center',
        minWidth: 0,
        paddingBottom: '7px',
        borderBottomWidth: '1px',
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 42%, transparent)',
        justifyContent: {
            default: 'space-between',
        },
    },
    toolbarActionsInner: {
        display: 'flex',
        minWidth: 0,
        flexWrap: 'wrap',
        gap: '8px',
        alignItems: 'center',
    },
    toolbarActionsInnerNoWrap: {
        display: 'flex',
        flexWrap: 'nowrap',
        gap: '8px',
        alignItems: 'center',
        minWidth: 0,
    },
    toolbarSearchField: {
        display: 'flex',
        flex: '1 1 auto',
        alignItems: 'center',
        minWidth: 'calc(var(--mainFontSize) * 8)',
    },
    toolbarFields: {
        display: 'grid',
        gridTemplateColumns: {
            default: 'minmax(calc(var(--mainFontSize) * 9), 0.34fr) minmax(0, 1fr)',
            '@media screen and (max-width: 600px)': '1fr',
        },
        minWidth: 0,
        gap: '6px',
        alignItems: 'start',
        width: {
            '@media screen and (max-width: 600px)': '100%',
        },
    },
    toolbarField: {
        display: 'flex',
        flexWrap: 'nowrap',
        gap: '8px',
        alignItems: 'center',
        minWidth: 0,
        width: {
            '@media screen and (max-width: 600px)': '100%',
        },
    },
    toolbarInput: {
        width: '100%',
        minWidth: 0,
        margin: 0,
        height: 'calc(var(--mainFontSize) * 1.9)',
        paddingInline: '8px',
    },
    toolbarSelect: {
        flex: '1 1 auto',
        cursor: 'pointer',
    },
    toolbarFilters: {
        minWidth: 0,
    },
    bulkSelectedCount: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 'calc(var(--mainFontSize) * 4.8)',
        minHeight: 'calc(var(--mainFontSize) * 1.7)',
        margin: 0,
        padding: '3px 6px',
        color: 'var(--SmartThemeEmColor)',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        borderRadius: '5px',
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
        fontWeight: 600,
        lineHeight: 1,
        whiteSpace: 'nowrap',
    },
    panelRow: {
        minWidth: 0,
    },
    panelRowGrid: {
        gap: '6px',
    },
    panelCell: {
        minWidth: 0,
    },
});
