import * as stylex from '@stylexjs/stylex';

const narrowScreen = '@media screen and (max-width: 800px)';
const shellChromeNarrow = '@container (max-width: 1180px)';

export const workspacePanelStyles = stylex.create({
    statusBadge: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        borderRadius: '999px',
        fontSize: 'calc(var(--mainFontSize) * 0.76)',
        lineHeight: 1.15,
        padding: '2px 8px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 70%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 82%, transparent)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 80%, var(--SmartThemeBlurTintColor) 20%)',
    },
    statusBadgeLoading: {
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 42%, transparent)',
        color: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 72%, var(--SmartThemeBodyColor) 28%)',
    },
    statusBadgeError: {
        borderColor: 'color-mix(in srgb, var(--error-color, var(--ember-red)) 46%, transparent)',
        color: 'var(--error-color, var(--ember-red))',
    },
    legacySlotStatus: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        borderRadius: '999px',
        fontSize: 'calc(var(--mainFontSize) * 0.76)',
        lineHeight: 1.15,
    },
    legacySlotStatusReady: {
        color: 'var(--success-green)',
    },
    legacySlotStatusPending: {
        color: 'var(--warning)',
        fontWeight: 600,
    },
    legacySlot: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '8px',
    },
    legacySlotProtected: {
        opacity: 0.82,
    },
    recovery: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    recoveryActions: {
        display: 'inline-flex',
        flexWrap: 'wrap',
        gap: '6px',
        width: {
            default: null,
            [narrowScreen]: '100%',
        },
    },
    recoveryActionButton: {
        minHeight: '26px',
    },
});

export const workspaceShellStyles = stylex.create({
    chrome: {
        display: 'grid',
        gridTemplateColumns: 'minmax(0, 1fr) auto',
        alignItems: 'center',
        gap: '8px',
        height: '100%',
        padding: '4px 10px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 78%, transparent)',
        borderRadius: '0 0 9px 9px',
        background: 'linear-gradient(90deg, color-mix(in srgb, var(--SmartThemeQuoteColor) 13%, transparent), transparent 32%), color-mix(in srgb, var(--SmartThemeBlurTintColor) 90%, var(--black70a) 10%)',
        boxShadow: '0 4px 24px color-mix(in srgb, var(--black70a) 72%, transparent)',
        backdropFilter: 'blur(var(--SmartThemeBlurStrength))',
        WebkitBackdropFilter: 'blur(var(--SmartThemeBlurStrength))',
        containerType: 'inline-size',
        pointerEvents: 'auto',
    },
    context: {
        display: 'flex',
        minWidth: 0,
        alignItems: 'center',
        paddingInline: {
            default: '4px',
            [narrowScreen]: '2px',
        },
        overflow: 'hidden',
    },
    title: {
        flex: '1 1 auto',
        minWidth: 0,
        overflow: 'hidden',
        color: 'var(--SmartThemeBodyColor)',
        fontSize: 'calc(var(--mainFontSize) * 1.02)',
        fontWeight: 700,
        lineHeight: 1.25,
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    nav: {
        display: 'flex',
        flex: '0 0 auto',
        alignItems: 'center',
        gap: '4px',
        paddingBlock: '1px',
    },
    navButton: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 0,
        flex: '0 0 auto',
        minHeight: '28px',
        gap: '5px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: {
            default: 'color-mix(in srgb, var(--SmartThemeBorderColor) 70%, transparent)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 46%, var(--SmartThemeBorderColor) 54%)',
            ':focus-visible': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 46%, var(--SmartThemeBorderColor) 54%)',
        },
        borderRadius: '7px',
        padding: '3px 7px',
        backgroundColor: {
            default: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 76%, var(--black50a) 24%)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 13%, var(--SmartThemeBlurTintColor) 87%)',
            ':focus-visible': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 13%, var(--SmartThemeBlurTintColor) 87%)',
        },
        color: 'var(--SmartThemeBodyColor)',
        font: 'inherit',
        fontSize: 'calc(var(--mainFontSize) * 0.83)',
        lineHeight: 1.2,
        cursor: 'pointer',
        outline: {
            ':focus-visible': '1px solid var(--interactable-outline-color)',
        },
        outlineOffset: {
            ':focus-visible': '2px',
        },
    },
    navButtonActive: {
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 72%, var(--SmartThemeBorderColor) 28%)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 20%, var(--SmartThemeBlurTintColor) 80%)',
        boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--SmartThemeQuoteColor) 34%, transparent)',
    },
    navButtonLabel: {
        [shellChromeNarrow]: {
            position: 'absolute',
            width: '1px',
            height: '1px',
            margin: '-1px',
            overflow: 'hidden',
            clip: 'rect(0 0 0 0)',
            clipPath: 'inset(50%)',
            whiteSpace: 'nowrap',
        },
    },
    pinButton: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '24px',
        height: '24px',
        marginLeft: '-7px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 52%, transparent)',
            ':focus-visible': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 52%, transparent)',
        },
        borderRadius: '999px',
        color: {
            default: 'var(--SmartThemeBodyColor)',
            ':hover': 'var(--SmartThemeQuoteColor)',
            ':focus-visible': 'var(--SmartThemeQuoteColor)',
        },
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 14%, transparent)',
            ':focus-visible': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 14%, transparent)',
        },
        cursor: 'pointer',
        outline: {
            ':focus-visible': '1px solid var(--interactable-outline-color)',
        },
        outlineOffset: {
            ':focus-visible': '2px',
        },
    },
    pinButtonPressed: {
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 52%, transparent)',
        color: 'var(--SmartThemeQuoteColor)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 14%, transparent)',
    },
});

export const authoringStyles = stylex.create({
    panel: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        padding: '8px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 72%, transparent)',
        borderRadius: '10px',
        background: 'linear-gradient(color-mix(in srgb, var(--SmartThemeBlurTintColor) 86%, transparent), color-mix(in srgb, var(--SmartThemeBlurTintColor) 86%, transparent)), color-mix(in srgb, black 88%, var(--SmartThemeBodyColor) 12%)',
    },
    panelHeader: {
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: '8px',
    },
    panelKicker: {
        margin: 0,
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 72%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.86)',
    },
    panelHeaderText: {
        margin: 0,
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 72%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.86)',
    },
    panelHeaderTitle: {
        margin: 0,
        fontSize: 'calc(var(--mainFontSize) * 1.08)',
    },
    panelState: {
        borderRadius: '999px',
        padding: '3px 8px',
        fontSize: 'calc(var(--mainFontSize) * 0.84)',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 45%, transparent)',
        color: 'var(--SmartThemeQuoteColor)',
        whiteSpace: 'nowrap',
    },
    panelWarning: {
        borderRadius: '999px',
        padding: '3px 8px',
        fontSize: 'calc(var(--mainFontSize) * 0.84)',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 62%, transparent)',
        background: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 68%, transparent)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 92%, transparent)',
    },
    fields: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    fieldLabel: {
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 78%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.88)',
        fontWeight: 600,
    },
    sectionTitle: {
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 78%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.88)',
        fontWeight: 600,
    },
    fieldWarning: {
        color: 'var(--warning)',
    },
    panelActions: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '5px',
        alignItems: 'center',
        position: 'sticky',
        top: 0,
        zIndex: 2,
        marginInline: '-6px',
        borderTopWidth: '1px',
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 48%, transparent)',
        padding: '8px 6px 6px',
        background: 'linear-gradient(color-mix(in srgb, var(--SmartThemeBlurTintColor) 86%, transparent), color-mix(in srgb, var(--SmartThemeBlurTintColor) 86%, transparent)), color-mix(in srgb, black 88%, var(--SmartThemeBodyColor) 12%)',
        boxShadow: '0 8px 18px color-mix(in srgb, black 22%, transparent)',
    },
    saveButton: {
        background: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 26%, var(--SmartThemeBlurTintColor))',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 65%, transparent)',
        color: 'var(--SmartThemeBodyColor)',
        fontWeight: 700,
    },
    secondaryAction: {
        opacity: 0.82,
        filter: 'grayscale(0.35)',
    },
    toolAction: {
        opacity: 0.82,
        filter: 'grayscale(0.35)',
        background: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 72%, transparent)',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 58%, transparent)',
    },
    dangerZone: {
        display: 'flex',
        justifyContent: 'flex-start',
        paddingTop: '2px',
    },
    actionMenuWrap: {
        position: 'relative',
        display: 'inline-flex',
    },
    actionMenu: {
        position: 'absolute',
        top: 'calc(100% + 4px)',
        right: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
        minWidth: 'calc(var(--mainFontSize) * 13)',
        maxHeight: 'min(60vh, 420px)',
        overflowY: 'auto',
        padding: '4px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        borderRadius: '6px',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 92%, var(--SmartThemeBodyColor) 4%)',
        boxShadow: '0 10px 24px var(--SmartThemeShadowColor)',
        zIndex: 30,
    },
    actionMenuItem: {
        display: 'flex',
        alignItems: 'center',
        width: '100%',
        padding: '6px 10px',
        borderWidth: 0,
        borderRadius: '4px',
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 22%, transparent)',
        },
        color: 'var(--SmartThemeBodyColor)',
        fontSize: 'calc(var(--mainFontSize) * 0.92)',
        textAlign: 'left',
        cursor: 'pointer',
        outlineWidth: { ':focus-visible': '1px' },
        outlineStyle: { ':focus-visible': 'solid' },
        outlineColor: { ':focus-visible': 'var(--interactable-outline-color)' },
        outlineOffset: { ':focus-visible': '-1px' },
    },
    actionMenuItemDanger: {
        color: 'var(--SmartThemeEmColor)',
        borderTopWidth: '1px',
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 52%, transparent)',
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        marginTop: '2px',
        paddingTop: '7px',
        backgroundColor: {
            ':hover': 'color-mix(in srgb, red 26%, transparent)',
        },
    },
});

export const characterLibraryStyles = stylex.create({
    toolbar: {
        display: 'flex',
        flexDirection: 'column',
        gap: '7px',
        padding: '1px 0 2px',
    },
    toolbarAction: {
        margin: 0,
        minHeight: 'calc(var(--mainFontSize) * 1.85)',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 72%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 72%, transparent)',
    },
    toolbarActionIcon: {
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
    },
    toolbarActionCompact: {
        width: 'calc(var(--mainFontSize) * 1.9)',
        minWidth: 'calc(var(--mainFontSize) * 1.9)',
        minHeight: 'calc(var(--mainFontSize) * 1.9)',
        padding: '3px',
    },
    toolbarActionFull: {
        gap: '5px',
        paddingInline: '8px',
    },
    toolbarActions: {
        display: 'flex',
        flexWrap: 'nowrap',
        gap: '8px',
        alignItems: 'center',
        minWidth: 0,
        paddingBottom: '7px',
        borderBottomWidth: '1px',
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 42%, transparent)',
        justifyContent: {
            default: 'space-between',
        },
    },
    toolbarActionsInner: {
        display: 'flex',
        minWidth: 0,
        flexWrap: 'wrap',
        gap: '8px',
        alignItems: 'center',
    },
    toolbarActionsInnerNoWrap: {
        display: 'flex',
        flexWrap: 'nowrap',
        gap: '8px',
        alignItems: 'center',
        minWidth: 0,
    },
    toolbarSearchField: {
        display: 'flex',
        flex: '1 1 auto',
        alignItems: 'center',
        minWidth: 'calc(var(--mainFontSize) * 8)',
    },
    toolbarFields: {
        display: 'grid',
        gridTemplateColumns: {
            default: 'minmax(calc(var(--mainFontSize) * 9), 0.34fr) minmax(0, 1fr)',
            '@media screen and (max-width: 600px)': '1fr',
        },
        minWidth: 0,
        gap: '6px',
        alignItems: 'start',
        width: {
            '@media screen and (max-width: 600px)': '100%',
        },
    },
    toolbarField: {
        display: 'flex',
        flexWrap: 'nowrap',
        gap: '8px',
        alignItems: 'center',
        minWidth: 0,
        width: {
            '@media screen and (max-width: 600px)': '100%',
        },
    },
    toolbarInput: {
        width: '100%',
        minWidth: 0,
        margin: 0,
        height: 'calc(var(--mainFontSize) * 1.9)',
        paddingInline: '8px',
    },
    toolbarSelect: {
        flex: '1 1 auto',
        cursor: 'pointer',
    },
    toolbarFilters: {
        minWidth: 0,
    },
    bulkSelectedCount: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 'calc(var(--mainFontSize) * 4.8)',
        minHeight: 'calc(var(--mainFontSize) * 1.7)',
        margin: 0,
        padding: '3px 6px',
        color: 'var(--SmartThemeEmColor)',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        borderRadius: '5px',
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
        fontWeight: 600,
        lineHeight: 1,
        whiteSpace: 'nowrap',
    },
    panelRow: {
        minWidth: 0,
    },
    panelRowGrid: {
        gap: '6px',
    },
    panelCell: {
        minWidth: 0,
    },
});
