import * as stylex from '@stylexjs/stylex';

const narrowScreen = '@media (max-width: 768px)';
const motionOk = '@media (prefers-reduced-motion: no-preference)';

const fadeIn = stylex.keyframes({
    from: { opacity: 0 },
    to: { opacity: 1 },
});
const pulse = stylex.keyframes({
    '0%, 100%': { opacity: 1 },
    '50%': { opacity: 0.3 },
});

/**
 * World Info workbench visual system — "Ember Codex".
 *
 * Surfaces layer `--SmartThemeBlurTintColor` at different mixes; the ember
 * accent (`--SmartThemeQuoteColor`) marks activation state, selection rails,
 * and primary actions. Micro kicker labels give the editor its structure.
 */
export const worldInfoWorkbenchStyles = stylex.create({
    root: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        minHeight: 0,
        flex: {
            default: '1 1 auto',
            [narrowScreen]: '1 1 0',
        },
        height: {
            default: '100%',
            [narrowScreen]: 'auto',
        },
        maxHeight: {
            [narrowScreen]: '100%',
        },
        overflow: 'hidden',
    },

    /* ---------- Global activation banner ---------- */
    global: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        padding: '8px 10px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 26%, var(--SmartThemeBorderColor) 74%)',
        borderRadius: 'var(--rounded-lg, 10px)',
        background: 'linear-gradient(90deg, color-mix(in srgb, var(--SmartThemeQuoteColor) 10%, transparent), transparent 55%), color-mix(in srgb, var(--SmartThemeBlurTintColor) 88%, var(--black70a) 12%)',
        boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--SmartThemeQuoteColor) 8%, transparent)',
    },
    globalIcon: {
        flex: '0 0 auto',
        width: '34px',
        alignSelf: 'center',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        aspectRatio: '1',
        borderRadius: '9px',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 16%, var(--SmartThemeBlurTintColor) 84%)',
        color: 'var(--SmartThemeQuoteColor)',
        fontSize: 'calc(var(--mainFontSize) * 1.05)',
    },
    globalField: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        gap: '3px',
        flex: '1 1 auto',
        minWidth: '140px',
        alignSelf: 'stretch',
    },
    globalLabel: {
        fontSize: 'calc(var(--mainFontSize) * 0.72)',
        fontWeight: 700,
        letterSpacing: '0.08em',
        textTransform: 'uppercase',
        color: 'var(--SmartThemeQuoteColor)',
        opacity: 0.82,
    },
    globalSelect: {
        margin: 0,
        height: 'auto',
        maxHeight: '88px',
        overflowY: 'auto',
        borderRadius: '8px',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 80%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 72%, var(--black70a) 28%)',
    },
    globalMeta: {
        flex: '0 0 auto',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        justifyContent: 'center',
        gap: '4px',
        maxWidth: '46%',
    },
    globalCount: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '5px',
        padding: '2px 9px',
        borderRadius: '999px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 48%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 14%, transparent)',
        color: 'var(--SmartThemeQuoteColor)',
        fontSize: 'calc(var(--mainFontSize) * 0.76)',
        fontWeight: 700,
        whiteSpace: 'nowrap',
    },
    pulseDot: {
        flex: '0 0 auto',
        width: '6px',
        height: '6px',
        borderRadius: '999px',
        backgroundColor: 'currentColor',
        boxShadow: '0 0 6px currentColor',
        animationName: { default: null, [motionOk]: pulse },
        animationDuration: { default: null, [motionOk]: '2.4s' },
        animationIterationCount: { default: null, [motionOk]: 'infinite' },
    },
    globalCountMuted: {
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 70%, transparent)',
        backgroundColor: 'transparent',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 62%, transparent)',
    },
    globalSummary: {
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 68%, transparent)',
        textAlign: 'right',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        maxWidth: '100%',
    },
    rulesToggle: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '5px',
        padding: '3px 9px',
        borderRadius: '999px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: {
            default: 'color-mix(in srgb, var(--SmartThemeBorderColor) 70%, transparent)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 46%, var(--SmartThemeBorderColor) 54%)',
        },
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 12%, transparent)',
        },
        color: 'var(--SmartThemeBodyColor)',
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
        cursor: 'pointer',
        whiteSpace: 'nowrap',
    },
    rulesToggleIcon: {
        fontSize: '0.85em',
        color: 'var(--SmartThemeQuoteColor)',
    },
    rulesHint: {
        margin: '4px 2px 0',
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 58%, transparent)',
    },

    /* ---------- Book header command bar ---------- */
    bookHeader: {
        display: 'flex',
        flexDirection: 'column',
        gap: '7px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 68%, transparent)',
        borderRadius: 'var(--rounded-lg, 10px)',
        padding: '8px 10px',
        background: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 88%, var(--black70a) 12%)',
    },
    bookRow: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '6px',
        alignItems: 'center',
        minWidth: 0,
    },
    bookRowTools: {
        paddingTop: '7px',
        borderTopWidth: '1px',
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 38%, transparent)',
    },
    bookIcon: {
        flex: '0 0 auto',
        alignSelf: 'center',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '30px',
        aspectRatio: '1',
        borderRadius: '7px',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 14%, var(--SmartThemeBlurTintColor) 86%)',
        color: 'var(--SmartThemeQuoteColor)',
        fontSize: 'calc(var(--mainFontSize) * 0.85)',
    },
    flexRow: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
        alignItems: 'center',
    },
    flexInput: {
        minWidth: 0,
        flex: '1 1 140px',
    },
    bookSelect: {
        margin: 0,
        height: 'calc(var(--mainFontSize) * 1.95)',
        borderRadius: '8px',
        fontWeight: 700,
        fontSize: 'calc(var(--mainFontSize) * 0.95)',
    },
    countBadge: {
        display: 'inline-flex',
        alignItems: 'center',
        padding: '2px 8px',
        borderRadius: '999px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 62%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 66%, transparent)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 76%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.74)',
        fontWeight: 600,
        whiteSpace: 'nowrap',
    },
    spacer: {
        flex: '1 1 auto',
    },
    divider: {
        alignSelf: 'stretch',
        width: '1px',
        marginBlock: '3px',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 60%, transparent)',
    },

    /* ---------- Buttons ---------- */
    button: {
        width: 'auto',
        minWidth: '34px',
        flex: '0 0 auto',
        margin: 0,
        gap: '5px',
        padding: '4px 10px',
        minHeight: '30px',
        borderRadius: '7px',
        fontSize: 'calc(var(--mainFontSize) * 0.84)',
        fontWeight: 600,
        whiteSpace: 'nowrap',
        filter: 'none',
        transition: {
            [motionOk]: 'background-color 0.15s ease, border-color 0.15s ease, color 0.15s ease',
        },
    },
    buttonPrimary: {
        backgroundColor: {
            default: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 22%, var(--SmartThemeBlurTintColor) 78%)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 32%, var(--SmartThemeBlurTintColor) 68%)',
        },
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 58%, transparent)',
        color: 'var(--SmartThemeBodyColor)',
    },
    buttonGhost: {
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 12%, transparent)',
        },
        borderColor: {
            default: 'color-mix(in srgb, var(--SmartThemeBorderColor) 55%, transparent)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 42%, transparent)',
        },
    },
    buttonGhostActive: {
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 60%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 16%, transparent)',
        color: 'var(--SmartThemeQuoteColor)',
    },
    buttonIcon: {
        width: '30px',
        minWidth: '30px',
        padding: '4px',
        fontSize: 'calc(var(--mainFontSize) * 0.85)',
    },
    buttonDanger: {
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--error-color, var(--ember-red)) 18%, transparent)',
        },
        borderColor: {
            default: 'color-mix(in srgb, var(--error-color, var(--ember-red)) 42%, transparent)',
            ':hover': 'color-mix(in srgb, var(--error-color, var(--ember-red)) 64%, transparent)',
        },
        color: {
            default: 'color-mix(in srgb, var(--error-color, var(--ember-red)) 82%, var(--SmartThemeBodyColor) 18%)',
            ':hover': 'var(--SmartThemeBodyColor)',
        },
    },
    buttonIconSlot: {
        fontSize: '0.9em',
        lineHeight: 1,
    },

    /* ---------- Overflow menu ---------- */
    menuWrap: {
        position: 'relative',
        display: 'inline-flex',
        flex: '0 0 auto',
    },
    menu: {
        position: 'absolute',
        top: 'calc(100% + 5px)',
        right: 0,
        zIndex: 40,
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
        minWidth: 'calc(var(--mainFontSize) * 11.5)',
        padding: '4px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 85%, transparent)',
        borderRadius: '9px',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 94%, var(--SmartThemeBodyColor) 6%)',
        boxShadow: '0 12px 28px var(--SmartThemeShadowColor)',
    },
    menuItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        width: '100%',
        margin: 0,
        padding: '6px 9px',
        borderWidth: 0,
        borderRadius: '6px',
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 18%, transparent)',
        },
        color: 'var(--SmartThemeBodyColor)',
        fontSize: 'calc(var(--mainFontSize) * 0.85)',
        textAlign: 'left',
        whiteSpace: 'nowrap',
        cursor: 'pointer',
        filter: 'none',
    },
    menuItemIcon: {
        width: '14px',
        textAlign: 'center',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 62%, transparent)',
        fontSize: '0.9em',
    },
    menuSeparator: {
        margin: '3px 6px',
        borderTopWidth: '1px',
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 55%, transparent)',
    },

    /* ---------- Search ---------- */
    searchWrap: {
        position: 'relative',
        flex: '1 1 150px',
        minWidth: '120px',
        display: 'flex',
        alignItems: 'center',
    },
    searchIcon: {
        position: 'absolute',
        left: '9px',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 48%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
        pointerEvents: 'none',
    },
    searchInput: {
        width: '100%',
        margin: 0,
        height: 'calc(var(--mainFontSize) * 1.95)',
        paddingLeft: 'calc(var(--mainFontSize) * 1.8)',
        borderRadius: '8px',
    },
    sortSelect: {
        margin: 0,
        width: 'auto',
        height: 'calc(var(--mainFontSize) * 1.95)',
        borderRadius: '8px',
        flex: '0 0 auto',
        minWidth: '112px',
    },

    /* ---------- Split body ---------- */
    body: {
        display: 'grid',
        gridTemplateColumns: {
            default: 'minmax(230px, 0.9fr) minmax(300px, 1.25fr)',
            [narrowScreen]: '1fr',
        },
        gap: '10px',
        minHeight: 0,
        flex: {
            default: '1 1 auto',
            [narrowScreen]: '1 1 0',
        },
        animationName: { default: null, [motionOk]: fadeIn },
        animationDuration: { default: null, [motionOk]: '0.22s' },
        animationTimingFunction: { default: null, [motionOk]: 'ease-out' },
    },
    pane: {
        minHeight: 0,
        minWidth: 0,
        display: 'flex',
        flexDirection: 'column',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 62%, transparent)',
        borderRadius: 'var(--rounded-lg, 10px)',
        background: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 82%, var(--black70a) 18%)',
        overflow: 'hidden',
    },
    paneHidden: {
        display: 'none',
    },
    listHead: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '8px',
        padding: '8px 12px 6px',
        borderBottomWidth: '1px',
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 42%, transparent)',
    },
    listHeadTitle: {
        fontSize: 'calc(var(--mainFontSize) * 0.72)',
        fontWeight: 700,
        letterSpacing: '0.08em',
        textTransform: 'uppercase',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 58%, transparent)',
    },
    listHeadCount: {
        fontSize: 'calc(var(--mainFontSize) * 0.72)',
        fontWeight: 700,
        color: 'var(--SmartThemeQuoteColor)',
        fontVariantNumeric: 'tabular-nums',
    },
    list: {
        overflowY: 'auto',
        minHeight: 0,
        flex: '1 1 auto',
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        padding: '8px',
        overscrollBehavior: {
            [narrowScreen]: 'contain',
        },
        maskImage: 'linear-gradient(180deg, transparent 0px, black 9px, black calc(100% - 9px), transparent 100%)',
    },
    listFoot: {
        flex: '0 0 auto',
        padding: '5px 10px 7px',
        borderTopWidth: '1px',
        borderTopStyle: 'solid',
        borderTopColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 30%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.68)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 40%, transparent)',
        textAlign: 'center',
        letterSpacing: '0.02em',
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },

    /* ---------- Entry rows ---------- */
    entryRow: {
        position: 'relative',
        display: 'flex',
        alignItems: 'stretch',
        gap: '8px',
        width: '100%',
        textAlign: 'left',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'transparent',
        borderRadius: '9px',
        padding: '8px 10px 8px 13px',
        backgroundColor: {
            default: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 60%, transparent)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 8%, var(--SmartThemeBlurTintColor) 92%)',
        },
        transform: {
            [motionOk]: { ':hover': 'translateY(-1px)' },
        },
        boxShadow: {
            ':hover': '0 4px 14px color-mix(in srgb, var(--SmartThemeShadowColor) 55%, transparent)',
        },
        color: 'inherit',
        cursor: 'pointer',
        transition: {
            [motionOk]: 'background-color 0.14s ease, border-color 0.14s ease, transform 0.14s ease, box-shadow 0.14s ease',
        },
        outline: {
            ':focus-visible': '1px solid var(--interactable-outline-color)',
        },
        outlineOffset: {
            ':focus-visible': '1px',
        },
    },
    entryRowSelected: {
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 10%, var(--SmartThemeBlurTintColor) 90%)',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 52%, transparent)',
    },
    entryRowDisabled: {
        opacity: 0.62,
    },
    entryRowChecked: {
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 9%, var(--SmartThemeBlurTintColor) 91%)',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 34%, transparent)',
    },
    entryRail: {
        position: 'absolute',
        left: '4px',
        top: '8px',
        bottom: '8px',
        width: '3px',
        borderRadius: '999px',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBodyColor) 22%, transparent)',
    },
    entryRailActive: {
        backgroundColor: 'transparent',
        backgroundImage: 'linear-gradient(180deg, var(--SmartThemeQuoteColor) 0%, color-mix(in srgb, var(--SmartThemeQuoteColor) 38%, transparent) 100%)',
        boxShadow: '0 0 6px color-mix(in srgb, var(--SmartThemeQuoteColor) 40%, transparent)',
    },
    entryRowInner: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '8px',
        width: '100%',
        minWidth: 0,
    },
    entryCheck: {
        flex: '0 0 auto',
        width: '16px',
        height: '16px',
        marginTop: '2px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 90%, var(--SmartThemeBodyColor) 10%)',
        borderRadius: '4px',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '0.68em',
        lineHeight: 1,
        color: 'transparent',
    },
    entryCheckOn: {
        backgroundColor: 'var(--SmartThemeQuoteColor)',
        color: 'var(--SmartThemeBlurTintColor)',
        borderColor: 'var(--SmartThemeQuoteColor)',
    },
    entryRowContent: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'stretch',
        gap: '4px',
        minWidth: 0,
        flex: '1 1 auto',
    },
    entryTitleRow: {
        display: 'flex',
        alignItems: 'baseline',
        gap: '6px',
        minWidth: 0,
    },
    statusDot: {
        flex: '0 0 auto',
        width: '7px',
        height: '7px',
        borderRadius: '999px',
        alignSelf: 'center',
        backgroundColor: 'var(--success-green)',
        boxShadow: '0 0 5px color-mix(in srgb, var(--success-green) 65%, transparent)',
        animationName: { default: null, [motionOk]: pulse },
        animationDuration: { default: null, [motionOk]: '2.8s' },
        animationIterationCount: { default: null, [motionOk]: 'infinite' },
    },
    statusDotOff: {
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBodyColor) 32%, transparent)',
        boxShadow: 'none',
        animationName: 'none',
    },
    entryTitle: {
        fontWeight: 650,
        fontSize: 'calc(var(--mainFontSize) * 0.92)',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        minWidth: 0,
    },
    constantBadge: {
        flex: '0 0 auto',
        alignSelf: 'center',
        padding: '0 6px',
        borderRadius: '999px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 42%, transparent)',
        color: 'var(--SmartThemeQuoteColor)',
        fontSize: 'calc(var(--mainFontSize) * 0.68)',
        fontWeight: 700,
    },
    entryChips: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '3px',
        minWidth: 0,
        maxHeight: 'calc(var(--mainFontSize) * 1.5)',
        overflow: 'hidden',
    },
    chip: {
        maxWidth: '130px',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        padding: '1px 7px',
        borderRadius: '5px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 62%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 70%, var(--black70a) 30%)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 78%, transparent)',
        fontFamily: 'var(--monoFontFamily)',
        fontSize: 'calc(var(--mainFontSize) * 0.7)',
    },
    chipMore: {
        color: 'var(--SmartThemeQuoteColor)',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 38%, transparent)',
    },
    chipMuted: {
        borderStyle: 'dashed',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 45%, transparent)',
    },
    entryMeta: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '4px 10px',
        fontFamily: 'var(--monoFontFamily)',
        fontSize: 'calc(var(--mainFontSize) * 0.72)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 55%, transparent)',
    },
    metaTag: {
        whiteSpace: 'nowrap',
    },
    metaTagAccent: {
        color: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 82%, var(--SmartThemeBodyColor) 18%)',
    },

    /* ---------- Multi-select bar ---------- */
    multiBar: {
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: '6px',
        padding: '7px 10px',
        borderBottomWidth: '1px',
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 30%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 8%, var(--SmartThemeBlurTintColor) 92%)',
        fontSize: 'calc(var(--mainFontSize) * 0.82)',
    },
    multiBarCount: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '5px',
        padding: '1px 8px',
        borderRadius: '999px',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 20%, transparent)',
        color: 'var(--SmartThemeQuoteColor)',
        fontWeight: 700,
        marginRight: '2px',
        whiteSpace: 'nowrap',
    },

    /* ---------- Editor ---------- */
    editor: {
        overflowY: 'auto',
        minHeight: 0,
        flex: '1 1 auto',
        padding: '12px 14px',
        display: 'flex',
        flexDirection: 'column',
        gap: '14px',
        overscrollBehavior: {
            [narrowScreen]: 'contain',
        },
        maskImage: 'linear-gradient(180deg, transparent 0px, black 10px, black calc(100% - 10px), transparent 100%)',
    },
    editorEmpty: {
        alignItems: 'center',
        justifyContent: 'center',
        opacity: 0.75,
        gap: '10px',
    },
    emptyIcon: {
        fontSize: 'calc(var(--mainFontSize) * 1.8)',
        color: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 55%, var(--SmartThemeBodyColor) 45%)',
    },
    editorSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    editorSectionHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '7px',
    },
    sectionIcon: {
        flex: '0 0 auto',
        color: 'var(--SmartThemeQuoteColor)',
        fontSize: 'calc(var(--mainFontSize) * 0.78)',
    },
    editorSectionTitle: {
        margin: 0,
        fontSize: 'calc(var(--mainFontSize) * 0.74)',
        fontWeight: 700,
        letterSpacing: '0.09em',
        textTransform: 'uppercase',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 66%, transparent)',
        whiteSpace: 'nowrap',
    },
    sectionRule: {
        flex: '1 1 auto',
        height: '1px',
        background: 'linear-gradient(90deg, color-mix(in srgb, var(--SmartThemeBorderColor) 70%, transparent), transparent)',
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: '3px',
        minWidth: '120px',
        flex: '0 0 auto',
    },
    fieldGrow: {
        flex: '1 1 140px',
    },
    fieldLabel: {
        fontSize: 'calc(var(--mainFontSize) * 0.8)',
        fontWeight: 600,
        letterSpacing: '0.015em',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 72%, transparent)',
    },
    checkboxRow: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '6px 14px',
        alignItems: 'center',
    },
    content: {
        minHeight: '200px',
        resize: 'vertical',
        padding: '10px 12px',
        borderRadius: '8px',
        fontFamily: 'var(--monoFontFamily)',
        fontSize: 'calc(var(--mainFontSize) * 0.88)',
        lineHeight: 1.65,
        backgroundColor: 'color-mix(in srgb, var(--black70a) 26%, var(--SmartThemeBlurTintColor) 74%)',
        backgroundImage: 'linear-gradient(90deg, color-mix(in srgb, var(--SmartThemeQuoteColor) 10%, transparent), transparent 3px)',
        backgroundRepeat: 'no-repeat',
    },
    macroBar: {
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: '4px',
    },
    macroChip: {
        padding: '1px 8px',
        borderRadius: '5px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: {
            default: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 40%, transparent)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 70%, transparent)',
        },
        backgroundColor: {
            default: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 7%, transparent)',
            ':hover': 'color-mix(in srgb, var(--SmartThemeQuoteColor) 16%, transparent)',
        },
        color: 'var(--SmartThemeQuoteColor)',
        fontFamily: 'var(--monoFontFamily)',
        fontSize: 'calc(var(--mainFontSize) * 0.72)',
        cursor: 'pointer',
        transition: {
            [motionOk]: 'background-color 0.12s ease, border-color 0.12s ease',
        },
    },
    macroHint: {
        marginLeft: 'auto',
        fontSize: 'calc(var(--mainFontSize) * 0.7)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 45%, transparent)',
        whiteSpace: 'nowrap',
    },

    /* ---------- Advanced accordion ---------- */
    advanced: {
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeBorderColor) 45%, transparent)',
        borderLeftWidth: '3px',
        borderLeftColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 34%, transparent)',
        borderRadius: '8px',
        padding: '7px 10px',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeBlurTintColor) 55%, transparent)',
    },
    advancedSummary: {
        display: 'flex',
        alignItems: 'center',
        gap: '7px',
        cursor: 'pointer',
        fontSize: 'calc(var(--mainFontSize) * 0.82)',
        fontWeight: 600,
        listStyle: 'none',
    },
    advancedChevron: {
        fontSize: '0.72em',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 50%, transparent)',
    },
    advancedChip: {
        marginLeft: 'auto',
        maxWidth: '60%',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        padding: '1px 8px',
        borderRadius: '999px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 40%, transparent)',
        color: 'var(--SmartThemeQuoteColor)',
        fontSize: 'calc(var(--mainFontSize) * 0.72)',
        fontWeight: 600,
    },
    advancedBody: {
        marginTop: '9px',
        display: 'flex',
        flexDirection: 'column',
        gap: '9px',
    },

    /* ---------- Ops & callouts ---------- */
    callout: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '8px',
        margin: 0,
        padding: '8px 10px',
        borderRadius: '8px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 28%, transparent)',
        backgroundColor: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 8%, transparent)',
        fontSize: 'calc(var(--mainFontSize) * 0.8)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 80%, transparent)',
    },
    calloutIcon: {
        flex: '0 0 auto',
        marginTop: '2px',
        color: 'var(--SmartThemeQuoteColor)',
        fontSize: '0.9em',
    },
    opsHint: {
        margin: 0,
        fontSize: 'calc(var(--mainFontSize) * 0.8)',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 60%, transparent)',
    },

    /* ---------- Empty states ---------- */
    empty: {
        padding: '32px 16px',
        textAlign: 'center',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '10px',
        color: 'color-mix(in srgb, var(--SmartThemeBodyColor) 66%, transparent)',
    },
    emptyBigIcon: {
        fontSize: 'calc(var(--mainFontSize) * 2.1)',
        color: 'color-mix(in srgb, var(--SmartThemeQuoteColor) 45%, var(--SmartThemeBodyColor) 55%)',
    },
    emptyAction: {
        width: 'auto',
        minWidth: 'max-content',
        flex: '0 0 auto',
        margin: 0,
        whiteSpace: 'nowrap',
    },
});
