import * as stylex from '@stylexjs/stylex';

const narrowScreen = '@media (max-width: 768px)';

export const worldInfoWorkbenchStyles = stylex.create({
    root: {
        display: 'flex',
        flexDirection: 'column',
        gap: 'var(--spacing-sm, 8px)',
        minHeight: 0,
        flex: {
            default: '1 1 auto',
            [narrowScreen]: '1 1 0',
        },
        height: {
            default: '100%',
            [narrowScreen]: 'auto',
        },
        maxHeight: {
            [narrowScreen]: '100%',
        },
        overflow: 'hidden',
    },
    global: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    globalSummary: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '8px',
        fontSize: '0.92em',
    },
    bookHeader: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in oklch, var(--SmartThemeBorderColor), transparent 30%)',
        borderRadius: 'var(--rounded-lg, 10px)',
        padding: '8px',
        background: 'color-mix(in oklch, var(--SmartThemeBlurTintColor), transparent 20%)',
    },
    flexRow: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
        alignItems: 'center',
    },
    flexInput: {
        minWidth: 0,
        flex: '1 1 140px',
    },
    button: {
        width: 'auto',
        minWidth: 'max-content',
        flex: '0 0 auto',
        margin: 0,
        whiteSpace: 'nowrap',
    },
    body: {
        display: 'grid',
        gridTemplateColumns: {
            default: 'minmax(220px, 0.9fr) minmax(280px, 1.2fr)',
            [narrowScreen]: '1fr',
        },
        gap: '10px',
        minHeight: 0,
        flex: {
            default: '1 1 auto',
            [narrowScreen]: '1 1 0',
        },
    },
    pane: {
        minHeight: 0,
        minWidth: 0,
        display: 'flex',
        flexDirection: 'column',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in oklch, var(--SmartThemeBorderColor), transparent 35%)',
        borderRadius: 'var(--rounded-lg, 10px)',
        background: 'color-mix(in oklch, var(--SmartThemeBlurTintColor), transparent 35%)',
    },
    paneHidden: {
        display: 'none',
    },
    list: {
        overflowY: 'auto',
        minHeight: 0,
        flex: '1 1 auto',
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
        padding: '6px',
        overscrollBehavior: {
            [narrowScreen]: 'contain',
        },
    },
    entryRow: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: '2px',
        width: '100%',
        textAlign: 'left',
        borderWidth: 0,
        borderStyle: 'none',
        borderRadius: '8px',
        padding: '8px',
        backgroundColor: {
            default: 'transparent',
            ':hover': 'color-mix(in oklch, var(--SmartThemeQuoteColor), transparent 88%)',
        },
        color: 'inherit',
        cursor: 'pointer',
    },
    entryRowSelected: {
        backgroundColor: 'color-mix(in oklch, var(--SmartThemeQuoteColor), transparent 88%)',
    },
    entryTitle: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        fontWeight: 600,
    },
    entryState: {
        fontSize: '0.75em',
        opacity: 0.8,
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in oklch, var(--SmartThemeBorderColor), transparent 20%)',
        borderRadius: '999px',
        padding: '0 6px',
    },
    entryStateDisabled: {
        opacity: 0.55,
    },
    entryMeta: {
        fontSize: '0.82em',
        opacity: 0.75,
    },
    editor: {
        overflowY: 'auto',
        minHeight: 0,
        flex: '1 1 auto',
        padding: '10px',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        overscrollBehavior: {
            [narrowScreen]: 'contain',
        },
    },
    editorEmpty: {
        alignItems: 'center',
        justifyContent: 'center',
        opacity: 0.7,
    },
    editorSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    editorSectionHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '8px',
    },
    editorSectionTitle: {
        margin: 0,
        fontSize: '0.95em',
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        minWidth: '120px',
        flex: '1 1 140px',
    },
    content: {
        minHeight: '180px',
        resize: 'vertical',
    },
    advanced: {
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'color-mix(in oklch, var(--SmartThemeBorderColor), transparent 40%)',
        borderRadius: '8px',
        padding: '6px 8px',
    },
    advancedSummary: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '8px',
        cursor: 'pointer',
    },
    advancedChip: {
        fontSize: '0.78em',
        opacity: 0.8,
    },
    advancedBody: {
        marginTop: '8px',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    multiBar: {
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: '6px',
        padding: '6px 8px',
        borderBottomWidth: '1px',
        borderBottomStyle: 'solid',
        borderBottomColor: 'color-mix(in oklch, var(--SmartThemeBorderColor), transparent 40%)',
        fontSize: '0.85em',
    },
    multiBarCount: {
        fontWeight: 600,
        marginRight: '4px',
    },
    entryRowInner: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '8px',
        width: '100%',
    },
    entryCheck: {
        flex: '0 0 auto',
        width: '14px',
        height: '14px',
        marginTop: '2px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: 'var(--SmartThemeBorderColor)',
        borderRadius: '3px',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '0.7em',
        lineHeight: 1,
    },
    entryCheckOn: {
        backgroundColor: 'var(--SmartThemeQuoteColor)',
        color: 'var(--SmartThemeBodyColor)',
        borderColor: 'var(--SmartThemeQuoteColor)',
    },
    entryRowContent: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: '2px',
        minWidth: 0,
        flex: '1 1 auto',
    },
    opsHint: {
        margin: 0,
        fontSize: '0.82em',
        opacity: 0.75,
    },
    empty: {
        padding: '24px 12px',
        textAlign: 'center',
        opacity: 0.7,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '8px',
    },
    emptyAction: {
        width: 'auto',
        minWidth: 'max-content',
        flex: '0 0 auto',
        margin: 0,
        whiteSpace: 'nowrap',
    },
});
