allowBuilds:
  '@astryxdesign/core': false
  protobufjs: false
overrides:
  protobufjs: 7.6.5
  lodash-es: 4.18.1
  nanoid: 3.3.18
  qs: 6.16.0
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@stylexjs/babel-plugin@0.19.1'
  - '@stylexjs/postcss-plugin@0.19.1'
  - '@stylexjs/shared@0.19.1'
  - '@stylexjs/stylex@0.19.1'
  - '@stylexjs/unplugin@0.19.1'
  - '@astryxdesign/core@0.6.2'
trustPolicy: no-downgrade
trustPolicyExclude:
  - protobufjs@6.11.6
  - semver@6.3.1
